version: '3.3'
services:
  db:
    image: mysql:5.7.41
    volumes:
      - ./sql:/var/lib/mysql
    
    ports:
      - "3307:3306"
    
    platform: linux/x86_64/v8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      web:
        ipv4_address: 202.202.0.18

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=202.202.0.18
      - PMA_PORT=3306
    networks:
      web:
        ipv4_address: 202.202.0.12
    
  wordpress:
    image: wordpress:5.5.3-php7.3
    ports:
      - "80:80"
    
    volumes:
      - ./wp-data:/var/www/html
      - ./wp/config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
    

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      web:
        ipv4_address: 202.202.0.16
  kali:
    image: gferrara8596/ns-kali
    networks:
      web:
        ipv4_address: 202.202.0.5
  
  firefox:
    image: jlesage/firefox
    ports:
      - "5800:5800"
    
    networks:
      web:
        ipv4_address: 202.202.0.11

networks:
  web:
    driver: bridge
    ipam:
      config:
        - subnet: 202.202.0.0/24

