version: '3.3'
services:
  db:
    image: mysql:5.7.41
    volumes:
      - ./sql:/var/lib/mysql
    
    ports:
      - "3307:3306"
    
    platform: linux/x86_64/v8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      web:
        ipv4_address: 193.20.1.2

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=172.18.1.2
      - PMA_PORT=3306
    networks:
      web:
        ipv4_address: 193.20.1.3

  wordpress:
    image: wordpress:5.5.3-php7.3
    ports:
      - "80:80" 
    volumes:
      - ./wp-data:/var/www/html
      - ./wp/config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      web:
        ipv4_address: 193.20.1.4
  kali:
    image: gferrara8596/ns-kali
    ports:
      - "5901:5901"
    networks:
      web:
        ipv4_address: 193.20.1.5
networks:
  web:
    driver: bridge
    ipam:
      config:
        - subnet: 193.20.1.1/24